tasks

diff --git a/processes_and_signals/11-manage_my_process b/processes_and_signals/11-manage_my_process
--- a/processes_and_signals/11-manage_my_process
+++ b/processes_and_signals/11-manage_my_process
@@ -1,7 +1,53 @@
 #!/usr/bin/env bash
-# Bash script Indefinitely writes I am alive! to the file /tmp/my_process
-while true;
-do
-    echo "I am alive!" > /tmp/my_process
-    sleep 2
-done
+#a manage_my_process Bash script that:
+#Indefinitely writes I am alive! to the file /tmp/my_process
+#In between every I am alive! message, the program should pause for 2 seconds
+
+pid_file="/var/run/my_process.pid"
+script_file="manage_my_process"
+
+start() {
+    if [ -f "$pid_file" ]; then
+        echo "Error: $script_file is already running."
+        exit 1
+    fi
+    
+    ./"$script_file" &
+    echo $! > "$pid_file"
+    echo "manage_my_process started."
+}
+
+stop() {
+    if [ ! -f "$pid_file" ]; then
+        echo "Error: $script_file is not running."
+        exit 1
+    fi
+    
+    pid=$(cat "$pid_file")
+    kill "$pid"
+    rm "$pid_file"
+    echo "manage_my_process stopped."
+}
+
+restart() {
+    stop
+    start
+    echo "manage_my_process restarted."
+}
+
+case "$1" in
+    start)
+        start
+        ;;
+    stop)
+        stop
+        ;;
+    restart)
+        restart
+        ;;
+    *)
+        echo "Usage: manage_my_process {start|stop|restart}"
+        exit 1
+        ;;
+esac
+
